### ISSUE TITLE
StuQ 算法与数据结构第一节作业提交处

### ISSUE THREAD

**Issue by AlgorithmStuQ** [StuQAlgorithm/AlgorithmHomework#1]
请在本 Issues 下提交第一节课作业

**提交格式参考：**

1. **提交人**（必填，格式为“学号-StuQ 官网用户名”）：168-Sean
2. **作业地址**（本期作业的 github 个人仓库）：[Sean 的第一节课作业地址](https://github.com/StuQAlgorithm/AlgorithmHomework/tree/master/1st)
3. **感想**（选填，可以写一下自己完成作业中遇到的一些坑以及解决思路）：XXXXXX

**Comment by AlgorithmStuQ** [comment]
**提交示例：**

提交人：168-Sean
作业地址：[Sean 的第一节课作业地址](https://github.com/StuQAlgorithm/AlgorithmHomework/tree/master/1st)
感想：XXXXXX

请大家在后面跟帖提交作业。

**Comment by s32n** [comment]
test
